using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Moq;
using HelloWorld;

namespace HelloWorld.Test
{
    [TestClass]
    public class HelloTest
    {
        private Hello helloTestInstance; 

        [TestInitialize]
        public void TestInitialize()
        {
            helloTestInstance = new Hello();
        }

        [TestMethod]
        public void MainTest()
        {
            Assert.Fail("autogenerated");
        }
    }
}