using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Moq;
using TestClassNamespace.Class1;

namespace TestClassNamespace.Class1.Test
{
    [TestClass]
    public class TestClass1Test
    {
        private TestClass1 testClass1TestInstance; 

        [TestInitialize]
        public void TestInitialize()
        {
            int p1 = default(int);
            double p2 = default(double);
            testClass1TestInstance = new TestClass1(p1, p2);
        }

        [TestMethod]
        public void GetIntTest()
        {
            int actual = testClass1TestInstance.GetInt(); 

            int expected = default(int);
            Assert.AreEqual(expected, actual);
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void DoSomethingTest()
        {
            int param1 = default(int);
            double param2 = default(double); 

            Assert.Fail("autogenerated");
        }
    }
}